### ISSUE TITLE
TOML being highlighted as SQL

### ISSUE THREAD

**Issue by brettcannon** [pybee/podium#72]
### Describe the bug

I have a Markdown code block labeled as "toml", but it's also getting classified as SQL, which is leading to incorrect highlighting.

### Steps to reproduce

- Create a slide with:

```toml
[[packages.wheels]]
name = "..."
upload-time = ...
url = "..."
path = "..."
size = ...
hashes = {...}
```

- Notice how "load-time" and "size" are in bold.

### Expected behavior

No bolding.

### Screenshots

![Image](https://github.com/user-attachments/assets/128e85b9-559c-4f8c-9cac-bdf738b7e072)

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```
